name: Atualizar AliExpress

on:
  schedule:
    - cron: '0 9 * * *' # Roda todos os dias de manhã
  workflow_dispatch: # Permite rodar manualmente clicando em um botão

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests
    - name: Rodar Robô
      env:
        ALI_APP_KEY: ${{ secrets.ALI_APP_KEY }}
        ALI_APP_SECRET: ${{ secrets.ALI_APP_SECRET }}
        ALI_TRACKING_ID: ${{ secrets.ALI_TRACKING_ID }}
      run: python update_products.py
    - name: Salvar CSV
      run: |
        git config --global user.name "Robô BuzzBuy"
        git config --global user.email "robo@buzzbuy.cloud"
        git add produtos_automaticos.csv
        git commit -m "Atualizando produtos do AliExpress" || echo "Sem mudanças"
        git push
